version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: go_app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: empleadosdb
      DB_PORT: 5432
      JWT_SECRET: qhfihgrgkjgnhanmhglhgutnbubefwrtahg
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    container_name: next_frontend
    ports:
      - "3001:3000"  # Next.js expone 3000 internamente, lo mapeamos al host en 3001
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://backend:3000
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: empleados_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: empleadosdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "empleadosdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
